version: "3"
services:
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "8000:8000"
    working_dir: /usr/src/weatherapp_frontend
    volumes:
      - ./frontend:/usr/src/weatherapp_frontend:cached

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "9000:9000"
    working_dir: /usr/src/weatherapp_backend
    volumes:
      - ./backend:/usr/src/weatherapp_backend:cached