version: "3"
services:
  frontend:
    build: ./frontend
    command: sh -c "npm install && npm start"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/usr/src/weatherapp/frontend:cached

  backend:
    build: ./backend
    command: sh -c "npm install && npm start"
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/usr/src/weatherapp/backend:cached